input_map: "data/Ti64_LR.npy"
n_colors: 4
scale: 4
model: 'han'
act: 'relu'
n_resblocks: 20
n_resgroups: 10
reduction: 16
n_feats: 128
res_scale: 1
save: 'data'
model_to_load: '/home/devendra/Desktop/BisQue_Modules/EBSDSR_Module/EBSDSR/src/model_weights/model_best.pt'
leak_value: 0.2

