input_map: "Ti64_LR.npy"
n_colors: 4
scale: 4
model: 'qrbsa_1d'
act: 'relu'
n_resblocks: 10
n_resgroups: 10
reduction: 16
n_feats: 128
res_scale: 1
save: 'data'
model_to_load: '/module/src/model_weights/model_best.pt'
leak_value: 0.2
